trigger:
  batch: false
  branches:
    include:
      - main
      - net48

pool:
  vmImage: ubuntu-latest

variables:
  - group: Nuget

steps:
  - pwsh: |
      Get-ChildItem -Path '$(Build.ArtifactStagingDirectory)' -Recurse -Include *.nupkg, *.snupkg | Remove-Item
      Get-ChildItem -Path '$(Build.SourcesDirectory)' -Recurse -Include *.nupkg, *.snupkg | Remove-Item
    displayName: Clear NuGet packages

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: Kros.KORM.slnx
      arguments: --configuration Release

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: Kros.KORM.slnx
      publishTestResults: false
      arguments: --configuration Release --logger trx --results-directory "$(Common.TestResultsDirectory)"

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '*.trx'
      searchFolder: $(Common.TestResultsDirectory)

  - ${{ if in(variables['Build.SourceBranchName'], 'main', 'net48') }}:

    - task: CopyFiles@2
      displayName: Copy package files to staging directory
      inputs:
        Contents: |
          **/*.nupkg
          **/*.snupkg
        TargetFolder: $(Build.ArtifactStagingDirectory)
        FlattenFolders: true

    - pwsh: |
        Get-ChildItem '$(Build.ArtifactStagingDirectory)/*.nupkg' | ForEach-Object {
          Write-Host 'Pushing package $($_.Name)'
          dotnet nuget push --api-key $(nugetOrgApiKey) --source 'https://api.nuget.org/v3/index.json'  --skip-duplicate $_.FullName
        }
      displayName: Push to NuGet.org
