trigger:
  batch: true
  branches:
    include:
    - master

pool: Default

resources:
  repositories:
    - repository: templates
      type: git
      name: DevShared/Templates

steps:
  - template: steps/agent-info.yml@templates
  - template: build-and-test.yml
