trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      ls -R -l $(Build.SourcesDirectory)
    displayName: List source folder

  - template: build-and-test.yml
