trigger:
  tags:
    include:
    - v*

pool: Default

resources:
  repositories:
    - repository: templates
      type: git
      name: DevShared/Templates

variables:
  - group: Nuget

steps:
  - template: steps/agent-info.yml@templates
  - template: steps/delete-nupkgs.yml@templates
  - template: build-and-test.yml

  - task: CopyFiles@2
    displayName: 'Copy package files to staging directory'
    inputs:
      Contents: |
        **/*.nupkg
        **/*.snupkg
      TargetFolder: '$(build.artifactStagingDirectory)'
      FlattenFolders: true

  - template: steps/nuget-push.yml@templates
    parameters:
      feed: '$(nuget.feed)'
