SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].Projects(
	[Id] [int] NOT NULL,
	[Name] [nvarchar](255),
	[UserId] [int] NOT NULL
CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED
(
	[Id] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ProjectDetails](
	[ProjectId] [int] NOT NULL,
	[Investor] [nvarchar](100),
	[Place] [nvarchar](50),
CONSTRAINT [PK_ProjectDetails] PRIMARY KEY CLUSTERED
(
	[ProjectId] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ProjectDetails] WITH CHECK ADD CONSTRAINT [FK_ProjectDetails_Projects] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Projects] ([Id])
ON DELETE CASCADE
GO