//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kros.KORM.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kros.KORM.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///
        ///CREATE DATABASE [Projects]
        /// CONTAINMENT = NONE
        ///GO
        ///
        ///ALTER DATABASE [Projects] SET COMPATIBILITY_LEVEL = 130
        ///GO
        ///
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        ///EXEC [Projects].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        ///end
        ///GO
        ///
        ///ALTER DATABASE [Projects] SET ANSI_NULL_DEFAULT OFF
        ///GO
        ///
        ///ALTER DATABASE [Projects] SET ANSI_NULLS OFF
        ///GO
        ///
        ///ALTER DATABASE [Projects] SET ANSI_PADDING OFF
        ///GO
        ///
        ///ALTER DATABASE [Projects] SET ANSI_WARNINGS OFF
        ///GO
        ///
        ///ALTER DATABASE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20190228001_InitDatabase {
            get {
                return ResourceManager.GetString("_20190228001_InitDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dui ante, pulvinar eget blandit sagittis, efficitur nec arcu. Mauris tristique et tellus at lobortis. Integer porttitor quis odio nec mattis. Aenean sed tincidunt leo. Quisque at tellus sit amet tellus interdum pellentesque nec et velit. Cras ut cursus ligula. Mauris in elit a elit tincidunt finibus. Praesent eget aliquet enim, vitae tristique nibh. Mauris porta lobortis pellentesque. Pellentesque convallis nibh a rutrum rhoncus. Sed sapie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigTextData {
            get {
                return ResourceManager.GetString("BigTextData", resourceCulture);
            }
        }
    }
}
