USE [master]
GO

CREATE DATABASE [Projects]
 CONTAINMENT = NONE
GO

ALTER DATABASE [Projects] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Projects].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Projects] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Projects] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Projects] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Projects] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Projects] SET ARITHABORT OFF
GO

ALTER DATABASE [Projects] SET AUTO_CLOSE ON
GO

ALTER DATABASE [Projects] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Projects] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Projects] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Projects] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Projects] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Projects] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Projects] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Projects] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Projects] SET  ENABLE_BROKER
GO

ALTER DATABASE [Projects] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Projects] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Projects] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Projects] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Projects] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Projects] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Projects] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Projects] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Projects] SET  MULTI_USER
GO

ALTER DATABASE [Projects] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Projects] SET DB_CHAINING OFF
GO

ALTER DATABASE [Projects] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Projects] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [Projects] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Projects] SET QUERY_STORE = OFF
GO

USE [Projects]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Projects] SET  READ_WRITE
GO