using System;

namespace Kros.KORM.ValueGeneration
{
    /// <summary>
    /// Indicates when a value for a property will be generated by the database.
    /// </summary>
    [Flags]
    public enum ValueGenerated
    {
        /// <summary>
        /// A value is never generated.
        /// </summary>
        Never = 0,

        /// <summary>
        /// A value is generated when an entity is added to the database.
        /// </summary>
        OnInsert = 1,

        /// <summary>
        /// A value is generated when an entity is updated to the database.
        /// </summary>
        OnUpdate = 2,

        /// <summary>
        /// A value is generated when an entity is added or update to the database.
        /// </summary>
        OnInsertOrUpdate = OnInsert | OnUpdate
    }
}
